version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./nginx2.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot
    entrypoint: /bin/sh
    command: -c "tail -F anything"
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      
  service1a:
    build: ./fastapi
    expose:
      - 80
    hostname: service1a

  service1b:
    build: ./fastapi
    expose:
      - 80
    hostname: service1b

  service2:
    build: ./fastapi
    expose:
      - 80
    hostname: service2