version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./tls:/tls
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
      
  service1a:
    build: ./fastapi
    expose:
      - 80
    hostname: service1a

  service1b:
    build: ./fastapi
    expose:
      - 80
    hostname: service1b

  service2:
    build: ./fastapi
    expose:
      - 80
    hostname: service2